server:
  port: 9090

spring:
  application:
    name: study-project
  devtools:
    livereload:
      enabled: true
      port: 35729
    restart:
      enabled: true
  data:
    redis:
#      host: host.docker.internal
      host: redis
      port: 6379
#      connect-timeout: 2000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG