version: "3"
services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "9090:9090"
    volumes:
      - .:/docker
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=dev
  redis:
    image: redis:latest
    container_name: my-redis
    hostname: my-redis
    ports:
      - "6379:6379"
