name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t my-docker-app:latest . -f docker/Dockerfile -d

      - name: Push Docker image
        run: |
          docker tag my-docker-image:latest ${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-app:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-app:latest